### ISSUE TITLE
RFE: unluckier support

### ISSUE THREAD

**Issue by redragon68** [linux-system-roles/nbde_client#21]
I would like to recommend adding support for clevis-luks-askpass@.path and clevis-luks-askpass@.service support.  This will allow unlocking of non / partitions upon boot.

**Comment by richm** [comment]
@sergio-correia Was this fixed as part of https://github.com/linux-system-roles/nbde_client/pull/79 and https://github.com/linux-system-roles/nbde_client/pull/81 ?

**Comment by sergio-correia** [comment]
Yes, I was just looking into this. This can be closed.
