### ISSUE TITLE
RFE: Dracut configurations

### ISSUE THREAD

**Issue by redragon68** [linux-system-roles/nbde_client#22]
I would like to recommend adding support for defining dracut parameters for ip, both static and dhcp.  Also supporting the option of adding support for configuring dracut for, omit_dracutmodules+="ifcfg", so that devices with multiple IPs are not disrupted by the dracut networking configuration.

You may want to add network flushing support so that the kernel networking configuration is flushed and replaced with the system networking configuration.  This prevents dracut/boot from destroying system network configurations such as multiple IPs on a single network interface, bonding, ect.

**Comment by richm** [comment]
@sergio-correia Does the current role support this?

**Comment by richm** [comment]
@sergio-correia was this fixed as part of https://github.com/linux-system-roles/nbde_client/pull/68 and https://github.com/linux-system-roles/nbde_client/pull/65 and https://github.com/linux-system-roles/nbde_client/pull/64 and some of the other dracut related changes?

**Comment by sergio-correia** [comment]
Yeah, I think we can consider that it has been fixed with those changes.
